language: cpp
compiler: 
 - gcc
 - clang
env:
 - DEBUG="debug"
 - DEBUG="nodebug"
 - LINKING="static"
before_install:
 - sudo apt-get install info install-info
 - sudo pip install cpp-coveralls
 - sudo pip install gcovr
 - wget ftp://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.52.tar.gz
 - tar -xvzf libmicrohttpd-0.9.52.tar.gz
 - cd libmicrohttpd-0.9.52
 - ./configure --prefix=/usr
 - make
 - sudo make install
 - cd ..
 - eval "${MATRIX_EVAL}"
script:
 - ./bootstrap
 - mkdir build
 - cd build
 - if [ $LINKING = "static" ]; then ../configure --enable-static --disable-fastopen; elif [ $DEBUG = "debug" ]; then ../configure --enable-debug --disable-shared --disable-fastopen; else ../configure --disable-fastopen; fi
 - make
 - make check
after_success:
  - if [ $DEBUG = "debug" ]; then ../ci-report-coverage; fi
matrix:
  exclude:
    - compiler: clang
      env: DEBUG="debug"
    - compiler: clang
      env: LINKING='static'
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
