language: cpp
os:
 - linux
 - osx
compiler: 
 - gcc
 - clang
env:
 - DEBUG="debug"
 - DEBUG="nodebug"
 - LINKING="static"
before_install:
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install info install-info; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo pip install cpp-coveralls; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo pip install gcovr; fi
 - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export CFLAGS='-mtune=generic'; fi
 - curl https://s3.amazonaws.com/libhttpserver/libmicrohttpd_releases/libmicrohttpd-0.9.59.tar.gz -o libmicrohttpd-0.9.59.tar.gz
 - tar -xvzf libmicrohttpd-0.9.59.tar.gz
 - cd libmicrohttpd-0.9.59
 - ./configure --disable-examples
 - make
 - sudo make install
 - cd ..
 - eval "${MATRIX_EVAL}"
script:
 - ./bootstrap
 - mkdir build
 - cd build
 - if [ $LINKING = "static" ]; then ../configure --enable-static --disable-fastopen; elif [ $DEBUG = "debug" ]; then ../configure --enable-debug --disable-shared --disable-fastopen; else ../configure --disable-fastopen; fi
 - make
 - make check
 - cat test/test-suite.log
after_success:
  - if [ $DEBUG = "debug" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then ../ci-report-coverage; fi
matrix:
  exclude:
    - compiler: clang
      env: DEBUG="debug"
    - compiler: clang
      env: LINKING='static'
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
